spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cache:
    type: redis
  redis:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    database: 0
  data:
    redis:
      repositories:
        enabled: false
  application:
    name: SHW
cas:
  server-url: http://login.greathiit.com
  login-url: http://login.greathiit.com/login
  logout-url: http://login.greathiit.com/logout
  exclude:
    - '/config'
    - '/student/down'
    - '/teacher/down'
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /config/actuator
  endpoint:
    health:
      show-details: always
datasource_url_end_str: ?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true