# 开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shw2${datasource_url_end_str}
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
logging:
  level: debug
  level.top: debug
cas:
  debug: true
  login-success-url: http://localhost:8090
  local-server-url: http://localhost:8080
  exclude:
    - '/config'
    - '/student/down'
    - '/teacher/down'
    - '/swagger'
    - '/webjars'
    - '/v2'
    - '/csrf'